//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR14
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tickets
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> SeatNumber { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
    
        public virtual Sessions Sessions { get; set; }
        public virtual Users Users { get; set; }
    }
}
